[build-system]
requires = ["setuptools>=61", "setuptools-scm[toml]>=8"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
version_scheme = "no-guess-dev"
local_scheme = "no-local-version"

[project]
name = "pedrocassol_pythonPackages"
dynamic = ["version"]
description = "Um pacote de rolagem de dados para jogos de RPG"
readme = "README.md"
requires-python = ">=3.9"
license = {text = "MIT"}

authors = [
    {name = "Pedro Cassol"}
]

classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]

[project.urls]
Homepage = "https://github.com/CTISM-Prof-Henry/pythonPackages"
